### ISSUE TITLE
Arch linux GTK2 package

### ISSUE THREAD

**Issue by mitchhentges** [raveit65/caja-actions#11]
Due to experiencing some bugs with mate-gtk3, I'm running "standard" mate for now. The Arch LInux `caja-actions` package seems to depend on `mate-gtk3`. Is it possible to have a second package for gtk2 mate? I'd rather not need to manually compile `caja-actions`.

Either way, thanks for building `caja-actions`!

**Comment by raveit65** [comment]
Sorry, this needs to done by archlinux maintainer.
