### ISSUE TITLE
Bash command substitution broken in Parameters field

### ISSUE THREAD

**Issue by duanemoody** [raveit65/caja-actions#33]
I've got a context menu item that depends on feeding Zenity the results of a Bash command:
<img width="699" alt="Screen Shot 2021-02-04 at 1 21 41 PM" src="https://user-images.githubusercontent.com/159372/106950679-fb09c000-66eb-11eb-91e9-2f93a1fb6a4a.png">
When the context menu is run, the resulting Zenity window's text is the unevaluated expression `$(md5sum '/path/to/filename')`
The equivalent command in a terminal evaluates properly and pops the Zenity window with the results of the expression:
`zenity --info --width=300 --text="$(md5sum /path/to/filename)"`
Using backtick notation instead of `"$()"` also does not work. What's the literal text generated then executed here such that the shell isn't obeying its own conventions for [command substitution](https://www.gnu.org/software/bash/manual/html_node/Command-Substitution.html)? Is there a way to see this?

**Comment by lgmventura** [comment]
I'm trying to make `caja-actions` work right now, but I can't even make the tool run the command in a terminal to be able to debug it. Did you manage to do that?
From what I understand, `md5sum` is itself a command and you want to pack into the parameters so its output will be the text parameter of Zenity?

**Comment by duanemoody** [comment]
This is correct, yes. At the command line (in either sh or bash),
`zenity --info --width=300 --text="$(md5sum /path/to/filename)"`
is working code which retrieves the md5 sum of /path/to/filename then populates the value of --text. Only in CACT (as well as its ancestor NACT) is the parameter somehow obfuscated such that the shell treats it as literal text instead of evaluating it.

**Comment by lgmventura** [comment]
This is not a solution, but rather a workaround: try creating a file `zenity_whatever.sh` with the content:
```
zenity --info --width=300 --text="$(md5sum "$1")"
```
So, instead of calling _zenity_ in `caja-actions-config-tool` command -> path, you call the zenity bash sh file you created. Then instead of giving all these parameters, now you pass only `%f`.

![image](https://user-images.githubusercontent.com/16710238/106962456-6e88ed00-673f-11eb-8e94-c99a815d17d4.png)

**Comment by duanemoody** [comment]
Yes, I did exactly that but the question remains as to what CACT is generating as the string it passes to the shell.

**Comment by lgmventura** [comment]
What string is it passing instead of the file path?

**Comment by duanemoody** [comment]
It's passing the literal string `$(md5sum /path/to/filename)` to --text instead of recognizing "$(expression)" is an expression and evaluating it by running md5sum on the pathed filename.
<img width="379" alt="Screen Shot 2021-02-04 at 3 31 44 PM" src="https://user-images.githubusercontent.com/159372/106963637-1da4d480-66fe-11eb-9a44-297ce0780c72.png">
<img width="607" alt="Screen Shot 2021-02-04 at 3 32 30 PM" src="https://user-images.githubusercontent.com/159372/106963718-3e6d2a00-66fe-11eb-961d-344b4fb43df0.png">

**Comment by lgmventura** [comment]
It looks like CACT still doesn't support evaluating expressions, but only those % parameters listed in the _Legend_. This is why I suggested letting the shell itself do it, when you call the `.sh` file from CACT. In this case, the only string CACT has to pass correctly is the %f (absolute path), which it does according to my few tests here.

**Comment by duanemoody** [comment]
CACT doesn't itself have to evaluate `$(expression)`, it just has to pass it to the shell (after substituting the values for its own % tokens) which will do it itself. That's what's confusing me.

**Comment by raveit65** [comment]
Caja-action is moved to https://github.com/mate-desktop/caja-actions
And this repo reached EOL.
So closing the topic.
