### ISSUE TITLE
cact-ienvironment-tab.c:738: read from uninit local variable ?

### ISSUE THREAD

**Issue by dcb314** [raveit65/caja-actions#8]
cact-ienvironment-tab.c:738:52: warning: variable 'state' is uninitialized when used here [-Wuninitialized]

```
           gtk_cell_renderer_toggle_set_active( renderer, state );
```

**Comment by raveit65** [comment]
I do not see this warning here if building from master.

**Comment by dcb314** [comment]
Suggest have a look at the code. 

I am using a different compiler to the one you use.

**Comment by raveit65** [comment]
Suggest provide a patch.

**Comment by raveit65** [comment]
btw. there is no warning at fedora build server from yesterday.
https://kojipkgs.fedoraproject.org//packages/caja-actions/1.8.2/1.fc25/data/logs/x86_64/build.log

**Comment by dcb314** [comment]
Merely repeating an irrelevant fact won't advance your case.
I repeat, have a look at the code. Just by looking at it, I can see it is broken.

Hint: local variable state gets initialised around line 722, inside an
if (editable) condition.

Later, inside the else, where state is still random stack contents, state is used
at line 738.

Maybe you need to tweek your compiler settings to include flags -g -O2 -Wall -Wextra ?
