### ISSUE TITLE
Release v1.8.0 fails to compile

### ISSUE THREAD

**Issue by realflash** [raveit65/caja-actions#9]
Compiling with gtk2, this is what I get:

egg-sm-client-xsmp.c: In function ‘sm_client_xsmp_startup’:
egg-sm-client-xsmp.c:386:7: error: implicit declaration of function ‘gdk_set_sm_client_id’ [-Werror=implicit-function-declaration]
       gdk_set_sm_client_id (xsmp->client_id);
       ^
cc1: all warnings being treated as errors

**Comment by realflash** [comment]
Mint 17.1 MATE edition

**Comment by NiceandGently** [comment]
> cc1: all warnings being treated as errors
Why your compiler does this?

**Comment by realflash** [comment]
I'm not sure. I am a dumb user. I found this in Makefile:

AM_CFLAGS =  -Wall -Wmissing-prototypes  -ansi -Wno-overlength-strings -Wformat=2 -Werror

I understand that -Werror means "treat warnings as errors". But if I take it out, nothing changes. Where else could I look?

**Comment by realflash** [comment]
Actually I see there are lots of Makefiles in other directories, and all have -Werror in their AM_CFLAGS.

Here's some of the output from ./autogen.sh:

```
Running ./configure --enable-maintainer-mode ...
```

and in configure I see:

```        if test "${USE_MAINTAINER_MODE}" = "yes"; then

$as_echo "#define NA_MAINTAINER_MODE 1" >>confdefs.h

                AM_CPPFLAGS="${AM_CPPFLAGS} ${DISABLE_DEPRECATED} -DGSEAL_ENABLED"

                AM_CFLAGS="${AM_CFLAGS} -Werror"

                msg_maintainer_mode="enabled"
        fi
```

so I assume maintainer mode is enabled.

**Comment by NiceandGently** [comment]
No, -Werror means only warn.
Take a look at configure.
AM_CFLAGS = -Wall -Wmissing-prototypes -ansi -Wno-overlength-strings -Wformat=2 -Werror is the normal package setting which is from configure.ac
But something change that during generation of configure
Try 
```
NOCONFIGURE=1 ./autogen.sh
./configure
```

**Comment by NiceandGently** [comment]
You can also download the tarball from https://raveit65.fedorapeople.org/Mate/SOURCE/
Here you don't neef to run ./autogen.sh only configure.
This is a with 'make dist' created source which i use for package building in fedora.

**Comment by raveit65** [comment]
no response from reporter!
